included:
  - Simmer
  - SimmerTests
  - SimmerUITests

excluded:
  - DerivedData
  - .build

warning_threshold: 0

disabled_rules:
  - file_length
  - todo

opt_in_rules:
  - explicit_top_level_acl
  - redundant_type_annotation
  - explicit_enum_raw_value
  - trailing_comma
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

force_cast:
  severity: error

force_unwrapping:
  severity: error

type_body_length:
  warning: 200
  error: 300

identifier_name:
  min_length: 3
  excluded:
    - id
    - URL
    - x
    - y
    - fd
