included:
  - Simmer
  - SimmerTests
  - SimmerUITests

excluded:
  - DerivedData
  - .build

disabled_rules:
  - file_length
  - todo

opt_in_rules:
  - redundant_type_annotation
  - trailing_comma
  - force_unwrapping # Confirmed for SwiftLint 0.61.0

trailing_comma:
  mandatory_comma: true

type_body_length:
  warning: 200
  error: 300

function_body_length:
  warning: 50
  error: 80

line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

force_cast:
  severity: error

force_unwrapping:
  severity: error

identifier_name:
  min_length: 3
  excluded:
    - id
    - URL
    - x
    - y
    - fd
